# revision 31927
# category Package
# catalog-ctan /fonts/ipaex-type1
# catalog-date 2013-10-17 13:39:26 +0200
# catalog-license other-free
# catalog-version 0.3b
Name:		texlive-ipaex-type1
Version:	0.3b
Release:	9
Summary:	IPAex fonts converted to Type-1 format Unicode subfonts
Group:		Publishing
URL:		http://www.ctan.org/tex-archive/fonts/ipaex-type1
License:	OTHER-FREE
Source0:	http://mirrors.ctan.org/systems/texlive/tlnet/archive/ipaex-type1.tar.xz
Source1:	http://mirrors.ctan.org/systems/texlive/tlnet/archive/ipaex-type1.doc.tar.xz
BuildArch:	noarch
BuildRequires:	texlive-tlpkg
Requires(pre):	texlive-tlpkg
Requires(post):	texlive-kpathsea

%description
The package contains the IPAex Fonts converted into Unicode
subfonts in Type1 format, which is most suitable for use with
the CJK package. Font conversion was done with ttf2pt1.

%post
    %{_sbindir}/texlive.post

%postun
    if [ $1 -eq 0 ]; then
	%{_sbindir}/texlive.post
    fi

#-----------------------------------------------------------------------
%files
%{_texmfdistdir}/fonts/map/dvips/ipaex-type1/ipaex-type1.map
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-ot1.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-t1.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-ts1.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u00.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u01.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u02.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u03.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u04.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u1e.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u1f.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u20.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u21.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u22.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u23.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u24.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u25.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u26.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u27.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u29.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u2e.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u2f.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u30.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u31.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u32.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u33.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u34.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u35.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u36.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u37.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u38.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u39.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u3a.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u3b.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u3c.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u3d.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u3e.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u3f.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u40.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u41.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u42.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u43.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u44.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u45.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u46.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u47.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u48.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u49.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u4a.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u4b.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u4c.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u4d.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u4e.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u4f.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u50.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u51.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u52.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u53.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u54.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u55.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u56.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u57.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u58.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u59.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u5a.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u5b.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u5c.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u5d.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u5e.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u5f.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u60.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u61.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u62.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u63.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u64.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u65.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u66.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u67.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u68.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u69.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u6a.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u6b.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u6c.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u6d.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u6e.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u6f.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u70.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u71.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u72.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u73.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u74.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u75.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u76.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u77.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u78.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u79.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u7a.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u7b.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u7c.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u7d.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u7e.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u7f.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u80.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u81.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u82.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u83.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u84.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u85.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u86.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u87.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u88.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u89.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u8a.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u8b.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u8c.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u8d.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u8e.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u8f.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u90.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u91.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u92.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u93.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u94.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u95.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u96.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u97.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u98.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u99.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u9a.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u9b.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u9c.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u9d.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u9e.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-u9f.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-uf0.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-uf8.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-uf9.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-ufa.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-ufe.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-r-uff.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-ot1.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-t1.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-ts1.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u00.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u01.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u02.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u03.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u04.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u1e.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u1f.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u20.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u21.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u22.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u23.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u24.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u25.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u26.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u27.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u29.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u2e.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u2f.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u30.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u31.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u32.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u33.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u34.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u35.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u36.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u37.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u38.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u39.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u3a.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u3b.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u3c.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u3d.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u3e.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u3f.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u40.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u41.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u42.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u43.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u44.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u45.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u46.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u47.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u48.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u49.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u4a.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u4b.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u4c.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u4d.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u4e.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u4f.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u50.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u51.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u52.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u53.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u54.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u55.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u56.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u57.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u58.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u59.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u5a.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u5b.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u5c.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u5d.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u5e.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u5f.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u60.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u61.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u62.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u63.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u64.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u65.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u66.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u67.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u68.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u69.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u6a.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u6b.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u6c.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u6d.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u6e.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u6f.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u70.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u71.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u72.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u73.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u74.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u75.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u76.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u77.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u78.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u79.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u7a.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u7b.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u7c.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u7d.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u7e.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u7f.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u80.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u81.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u82.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u83.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u84.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u85.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u86.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u87.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u88.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u89.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u8a.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u8b.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u8c.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u8d.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u8e.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u8f.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u90.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u91.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u92.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u93.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u94.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u95.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u96.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u97.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u98.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u99.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u9a.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u9b.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u9c.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u9d.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u9e.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-u9f.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-uf8.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-uf9.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-ufa.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-ufe.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxg-ro-uff.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-ot1.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-t1.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-ts1.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u00.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u01.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u02.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u03.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u04.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u1e.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u1f.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u20.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u21.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u22.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u23.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u24.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u25.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u26.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u27.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u29.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u2e.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u2f.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u30.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u31.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u32.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u33.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u34.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u35.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u36.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u37.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u38.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u39.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u3a.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u3b.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u3c.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u3d.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u3e.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u3f.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u40.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u41.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u42.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u43.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u44.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u45.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u46.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u47.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u48.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u49.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u4a.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u4b.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u4c.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u4d.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u4e.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u4f.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u50.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u51.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u52.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u53.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u54.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u55.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u56.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u57.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u58.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u59.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u5a.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u5b.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u5c.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u5d.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u5e.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u5f.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u60.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u61.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u62.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u63.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u64.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u65.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u66.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u67.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u68.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u69.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u6a.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u6b.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u6c.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u6d.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u6e.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u6f.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u70.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u71.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u72.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u73.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u74.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u75.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u76.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u77.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u78.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u79.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u7a.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u7b.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u7c.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u7d.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u7e.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u7f.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u80.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u81.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u82.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u83.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u84.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u85.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u86.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u87.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u88.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u89.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u8a.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u8b.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u8c.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u8d.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u8e.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u8f.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u90.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u91.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u92.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u93.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u94.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u95.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u96.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u97.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u98.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u99.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u9a.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u9b.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u9c.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u9d.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u9e.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-u9f.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-uf0.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-uf8.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-uf9.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-ufa.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-ufe.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-r-uff.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-ot1.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-t1.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-ts1.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u00.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u01.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u02.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u03.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u04.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u1e.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u1f.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u20.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u21.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u22.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u23.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u24.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u25.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u26.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u27.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u29.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u2e.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u2f.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u30.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u31.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u32.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u33.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u34.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u35.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u36.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u37.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u38.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u39.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u3a.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u3b.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u3c.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u3d.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u3e.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u3f.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u40.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u41.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u42.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u43.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u44.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u45.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u46.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u47.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u48.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u49.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u4a.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u4b.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u4c.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u4d.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u4e.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u4f.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u50.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u51.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u52.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u53.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u54.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u55.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u56.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u57.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u58.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u59.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u5a.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u5b.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u5c.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u5d.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u5e.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u5f.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u60.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u61.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u62.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u63.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u64.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u65.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u66.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u67.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u68.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u69.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u6a.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u6b.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u6c.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u6d.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u6e.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u6f.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u70.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u71.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u72.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u73.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u74.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u75.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u76.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u77.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u78.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u79.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u7a.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u7b.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u7c.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u7d.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u7e.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u7f.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u80.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u81.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u82.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u83.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u84.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u85.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u86.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u87.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u88.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u89.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u8a.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u8b.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u8c.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u8d.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u8e.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u8f.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u90.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u91.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u92.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u93.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u94.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u95.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u96.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u97.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u98.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u99.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u9a.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u9b.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u9c.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u9d.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u9e.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-u9f.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-uf8.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-uf9.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-ufa.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-ufe.tfm
%{_texmfdistdir}/fonts/tfm/public/ipaex-type1/ipxm-ro-uff.tfm
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-ot1.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-t1.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-ts1.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u00.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u01.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u02.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u03.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u04.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u1e.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u1f.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u20.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u21.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u22.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u23.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u24.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u25.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u26.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u27.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u29.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u2e.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u2f.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u30.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u31.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u32.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u33.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u34.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u35.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u36.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u37.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u38.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u39.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u3a.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u3b.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u3c.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u3d.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u3e.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u3f.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u40.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u41.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u42.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u43.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u44.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u45.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u46.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u47.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u48.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u49.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u4a.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u4b.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u4c.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u4d.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u4e.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u4f.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u50.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u51.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u52.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u53.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u54.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u55.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u56.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u57.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u58.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u59.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u5a.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u5b.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u5c.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u5d.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u5e.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u5f.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u60.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u61.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u62.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u63.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u64.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u65.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u66.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u67.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u68.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u69.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u6a.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u6b.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u6c.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u6d.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u6e.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u6f.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u70.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u71.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u72.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u73.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u74.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u75.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u76.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u77.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u78.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u79.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u7a.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u7b.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u7c.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u7d.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u7e.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u7f.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u80.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u81.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u82.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u83.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u84.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u85.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u86.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u87.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u88.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u89.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u8a.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u8b.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u8c.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u8d.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u8e.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u8f.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u90.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u91.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u92.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u93.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u94.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u95.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u96.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u97.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u98.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u99.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u9a.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u9b.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u9c.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u9d.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u9e.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-u9f.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-uf0.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-uf8.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-uf9.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-ufa.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-ufe.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxg-r-uff.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-ot1.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-t1.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-ts1.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u00.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u01.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u02.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u03.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u04.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u1e.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u1f.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u20.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u21.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u22.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u23.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u24.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u25.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u26.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u27.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u29.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u2e.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u2f.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u30.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u31.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u32.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u33.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u34.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u35.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u36.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u37.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u38.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u39.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u3a.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u3b.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u3c.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u3d.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u3e.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u3f.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u40.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u41.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u42.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u43.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u44.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u45.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u46.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u47.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u48.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u49.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u4a.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u4b.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u4c.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u4d.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u4e.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u4f.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u50.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u51.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u52.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u53.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u54.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u55.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u56.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u57.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u58.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u59.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u5a.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u5b.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u5c.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u5d.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u5e.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u5f.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u60.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u61.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u62.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u63.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u64.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u65.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u66.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u67.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u68.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u69.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u6a.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u6b.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u6c.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u6d.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u6e.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u6f.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u70.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u71.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u72.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u73.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u74.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u75.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u76.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u77.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u78.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u79.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u7a.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u7b.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u7c.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u7d.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u7e.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u7f.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u80.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u81.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u82.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u83.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u84.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u85.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u86.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u87.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u88.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u89.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u8a.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u8b.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u8c.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u8d.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u8e.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u8f.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u90.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u91.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u92.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u93.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u94.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u95.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u96.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u97.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u98.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u99.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u9a.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u9b.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u9c.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u9d.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u9e.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-u9f.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-uf0.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-uf8.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-uf9.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-ufa.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-ufe.pfb
%{_texmfdistdir}/fonts/type1/public/ipaex-type1/ipxm-r-uff.pfb
%{_texmfdistdir}/tex/latex/ipaex-type1/c70ipxg.fd
%{_texmfdistdir}/tex/latex/ipaex-type1/c70ipxga.fd
%{_texmfdistdir}/tex/latex/ipaex-type1/c70ipxm.fd
%{_texmfdistdir}/tex/latex/ipaex-type1/c70ipxma.fd
%{_texmfdistdir}/tex/latex/ipaex-type1/ot1ipxg.fd
%{_texmfdistdir}/tex/latex/ipaex-type1/ot1ipxm.fd
%{_texmfdistdir}/tex/latex/ipaex-type1/t1ipxg.fd
%{_texmfdistdir}/tex/latex/ipaex-type1/t1ipxm.fd
%{_texmfdistdir}/tex/latex/ipaex-type1/ts1ipxg.fd
%{_texmfdistdir}/tex/latex/ipaex-type1/ts1ipxm.fd
%doc %{_texmfdistdir}/doc/fonts/ipaex-type1/LICENSE
%doc %{_texmfdistdir}/doc/fonts/ipaex-type1/README-en
%doc %{_texmfdistdir}/doc/fonts/ipaex-type1/README-ja
%doc %{_texmfdistdir}/doc/fonts/ipaex-type1/c70ipxg.fdx
%doc %{_texmfdistdir}/doc/fonts/ipaex-type1/c70ipxga.fdx
%doc %{_texmfdistdir}/doc/fonts/ipaex-type1/c70ipxm.fdx
%doc %{_texmfdistdir}/doc/fonts/ipaex-type1/c70ipxma.fdx
%doc %{_texmfdistdir}/doc/fonts/ipaex-type1/sample-ipaex-type1.pdf
%doc %{_texmfdistdir}/doc/fonts/ipaex-type1/sample-ipaex-type1.tex

#-----------------------------------------------------------------------
%prep
%setup -c -a0 -a1

%build

%install
mkdir -p %{buildroot}%{_texmfdistdir}
cp -fpar fonts tex doc %{buildroot}%{_texmfdistdir}
